-- create table if not exists user2 (id bigint generated by default as identity, name varchar(255),email varchar(255), created_at timestamp(6),  updated_at timestamp(6), primary key (id));

insert into user2 (`name`, `email`,`gender`,`created_at`,`updated_at`) values ('martin', 'martin@fastcampus.com','MALE', now(), now());

insert into user2 (`name`,`email`,`gender`,`created_at`,`updated_at`) values ('hongsa', 'hongsa@fastcampus.com','FEMALE', now(), now());

insert into user2 (`name`, `email`,`gender`,`created_at`,`updated_at`) values ('honglion', 'honglion@fastcampus.com','MALE', now(), now());